### ISSUE TITLE
Air-conditioner settings -  fixed air flow direction  and "light"

### ISSUE THREAD

**Issue by mlepa84** [gvigroux/hon#112]
First of all thank you very much  for this integration! It is great and I use it everyday for cooling in the summer and heating when its cold.

My indor units are:
AS25XCAHRA
AS50XCAHRA
, and they have a possibility to direct the airflow, that is especially important in case of heating (it should be set down). The integration allows me to turn on/off motion of the direction of the air flow, however it's not possible to set a static direction for example downwards. The Haier mobile app has those settings so this should be possible to configure in in the same way as the temperature and fan speed.

One more thing that I lack in the Home Assistant hon integration is the "light" setting, that allows me to turn on and off the temperature display on the indor units. It is a very bright white led light that is a pain in the bedroom :( This setting is possible to alter from the remote control, but not from the app, so I'm not sure if you are able to implement it, however this would also be a great feature!

Please let me know if I can be of any assistance in developing those functionalities - I would be glad to help.

**Comment by gvigroux** [comment]
Thanks for your support!
You can decide about the air flow by using services "hOn: Set wind direction vertical" or "hOn: Set wind direction horizontal". 

About the light settings, you should try the service "hOn: Set climate screen display" :)

**Comment by mlepa84** [comment]
In order to turn off the "display" on the indoor unit, I've added this button to the HA interface:
```
show_name: true
show_icon: true
type: button
tap_action:
  action: call-service
  service: hon.start_program
  target:
    entity_id: climate.badroom
  data:
    parameters: '{''screenDisplayStatus'':''0''}'
    program: iot_heat
entity: climate.salon
name: Bedroom - turn off display
icon: mdi:numeric
icon_height: 60px
```
