### ISSUE TITLE
Add controls for turning off AC light

### ISSUE THREAD

**Issue by qbait** [gvigroux/hon#141]
It would be very useful for a Goodnight scene to be able to turn off an AC light.

**Comment by arkadi222** [comment]
this doesn't work ?
```
service: hon.update_settings
data:
  parameters: >-
    {'screenDisplayStatus':'0'}
target:
  device_id: 
```

**Comment by MarcoEnd** [comment]
I am using the service switch on/off the light:

```
service: hon.climate_set_screen_display
target:
  device_id: xyz
data:
  screen_display: false
```

false = light off
true = light on

This integration uses services to control devices you can play around with the developer tools / services.
