### ISSUE TITLE
Temperature zone and time sensor refresh

### ISSUE THREAD

**Issue by BerlineQQ** [gvigroux/hon#204]
Hi,

Fridge: HSW79F18DIPT
I have problem with parameter Temperature zone 1 and temperature zone 2, it is the same.

Next problem is long response for open door sensor. It is possibility to improve time?

![Image](https://github.com/user-attachments/assets/2afe355d-e907-4d44-a2a5-8b7b99022044)

**Comment by BerlineQQ** [comment]
Sensor refresh i do by automation i paste here for another but temperature zone is still problem

```
alias: Refresh
description: ""
triggers:
  - seconds: /10
    trigger: time_pattern
conditions: []
actions:
  - target:
      entity_id:
        - binary_sensor.lodowka_door_status_zone_1
        - binary_sensor.lodowka_door_status_zone_2
    action: homeassistant.update_entity
    data: {}
mode: restart
```
