### ISSUE TITLE
Haier Washing machine: Unable to update parameter [spinSpeed]

### ISSUE THREAD

**Issue by wurst44** [gvigroux/hon#213]
Hello,

My Haier dryer programs work. 
But when starting this washing machine program,
```
wash_allergy_care:
  alias: Wash Allergy Care 60°
  description: ""
  sequence:
    - service: hon.start_program
      data:
        program: hqd_allergy
        parameters: >-{'temp':60,'spinSpeed':1400,'delayTime':0,'delayStatus':0,'haier_SoakPrewashSelection':0,'mainWashTime':10,'rinseIterations':3,'permanentPressStatus':0,'nightWashStatus':0}
      target:
        device_id: xxxx
```

I get the following warning and nothing starts, which makes less sense because I am in the range (1400, 60):
```
hass       | 2025-05-07 13:20:11.449 WARNING (MainThread) [custom_components.hon.device] Unable to update parameter [temp] with value [60] because not in range ['0', '20', '30', '40', '60', '90']. Use default instead.
hass       | 2025-05-07 13:20:11.450 WARNING (MainThread) [custom_components.hon.device] Unable to update parameter [spinSpeed] with value [1400] because not in range ['0', '1000', '1200', '1400', '400', '600', '800']. Use default instead.
```

Any ideas?
Thanks!
