### ISSUE TITLE
How to use "Send custom request" action

### ISSUE THREAD

**Issue by nicmela** [gvigroux/hon#217]
Hi,
I'm struggling undestanding how to format custom requests in order to use them as an action for my climate setup:

Right now i'm using this for the action "hOn: Send custom request":

```
action: hon.send_custom_request
target:
  device_id: f3afd203565ed6dacecd8ba2aacaxxxx
data:
  device: f3afd203565ed6dacecd8ba2aacaxxxx
  parameters: {"onOffStatus": "0"}

```
this code works (beep on the AC unit, and then is set to OFF). 

However if i try any other parameter, for example 

```
action: hon.send_custom_request
target:
  device_id: f3afd203565ed6dacecd8ba2aacaxxxx
data:
  device: f3afd203565ed6dacecd8ba2aacaxxxx
  parameters: {"windDirectionVertical": "2"}

```
the command it's ignored (no beep from AC unit).

I know I can use action: hon.update_settings to set vertical direction (and it works).... but I'm trying to use different parameters in order to enable HEALTH_HIGH and HEALTH_LOW vertical positions (1,3) which are blocked by action: hon.update_settings

Any hint on how to correctly format custom requests in order to send parameters?
