### ISSUE TITLE
[feature request] Climate - configure airflow fixed position using HA Thermostate's "features"

### ISSUE THREAD

**Issue by kajak4u** [gvigroux/hon#222]
The climate can be configured with "features". Unfortunately for airflow we only have a few settings: "off", "horizontal", "vertical" and "both":

![Image](https://github.com/user-attachments/assets/0d0f8f4a-b6f9-4e47-aa0c-fd71165f90e2)

My climate (as35s2sf1fa_wh) supports setting a fixed position in both direction. It would be great if the integration allows me to read the current state and change it, via built-in option for thermostates.

**AS IS**:

```
type: thermostat
entity: climate.as35s2sf1fa_wh
name: Sterowanie
features:
[...]
  - style: dropdown
    type: climate-swing-modes
    swing_modes:
      - "off"
      - both
      - vertical
      - horizontal
```

**TO BE** (example):

```
type: thermostat
entity: climate.as35s2sf1fa_wh
name: Sterowanie
features:
[...]
  - style: dropdown
    type: climate-swing-modes-horizontal
    airflow_modes:
      - 1 (left)
      - 2
      - 3
      - 4
      - 5 (right)
      - swing_horizontal
  - style: dropdown
    type: climate-swing-modes-vertical
    airflow_modes:
      - 1 (bottom)
      - 2
      - 3
      - 4
      - 5 (top)
      - swing_vertical
```
