### ISSUE TITLE
Poll light status after calling a service or use optimistic local state

### ISSUE THREAD

**Issue by Marcocanc** [gvigroux/hon#54]
I'm currently using this integration with the Haier Wine cooler, primarily to control its light.
I have wrapped a template light around the service and sensors, however the status is not immediately updated after changing its state which results in the switch flicking back until the next polling request which makes it reflect the correct state.
It would be great if the integration could trigger an extra status query after calling the service or alternatively assume an optimistic temporary state until the next request is done via polling.

This is the template code I'm using:
```
light:
  - platform: template
    lights:
      wine_cooler_light:
        unique_id: wine_cooler_light
        friendly_name: "Wine Cooler Light"
        value_template: "{{ states('sensor.cooler_light_status') }}"
        turn_on:
          service: hon.turn_on_cooler_lights
          data:
            device: xxxxxxxxxxxxxxxxxx
        turn_off:
          service: hon.turn_off_cooler_lights
          data:
            device: xxxxxxxxxxxxxxxxxx
```
